name: release-$(Date:yyyyMMdd).$(Rev:r)

trigger: none
pr: none

parameters:
  - name: initialProductionRelease
    displayName: First production release (no versioned production currently deployed)
    type: boolean
    default: false

extends:
  template: templates/pipeline/release.yml
  parameters:
    initialProductionRelease: ${{ parameters.initialProductionRelease }}
