name: validate-$(Date:yyyyMMdd).$(Rev:r)

trigger:
  branches:
    include:
      - release/*
      - hotfix/*

# Azure Repos PR validation is configured with Branch Policy > Build validation.
pr: none

resources:
  repositories:
    - repository: policy
      type: git
      name: cicd-demo
      ref: refs/heads/main

extends:
  template: pipelines/templates/pipeline/root.yml@policy
  parameters:
    mode: validate
