name: release-$(Date:yyyyMMdd).$(Rev:r)

trigger: none
pr: none

parameters:
  - name: initialProductionRelease
    displayName: First production release with no versioned application currently deployed
    type: boolean
    default: false

resources:
  repositories:
    - repository: policy
      type: git
      name: cicd-demo
      ref: refs/heads/main

extends:
  template: pipelines/templates/pipeline/root.yml@policy
  parameters:
    mode: release
    initialProductionRelease: ${{ parameters.initialProductionRelease }}
